---
title: 'Hyper Enrichment (hypeR)'
subtitle: 'Weighted Gene Co-expression Analysis'
author: 'Anthony Federico, Stefano Monti'
date: 'Last Modified: `r Sys.Date()`'
output:
  html_document:
    theme: united
    toc: true
    toc_float: true
    toc_depth: 1
    code_folding: hide
    df_print: paged
---


```{r setup, echo=FALSE, message=FALSE}
knitr::opts_chunk$set(warning=FALSE, message=FALSE)
library(kableExtra)
```



# NON-CARC
##  {.tabset .tabset-fade}


### M0 
```{r 98972949884, fig.width=8.25, fig.align='center'}
hyp_obj <- tabsets[['NON-CARC']][['M0']] 



hyp_obj %>%
hyp_hmap(top=15,return_plots=1,show_plots=0)


df <- hyp_obj$as.data.frame()
df$label.abrv <- substr(df$label, 1, 30) 
col_ix <- match(c('pval', 'fdr', 'label.abrv'), colnames(df))
df <- df[, c(col_ix, (1:ncol(df))[-col_ix])]
df$label <- NULL
rownames(df) <- NULL
df

```


### M1 
```{r 31648048732, fig.width=8.25, fig.align='center'}
hyp_obj <- tabsets[['NON-CARC']][['M1']] 



hyp_obj %>%
hyp_hmap(top=15,return_plots=1,show_plots=0)


df <- hyp_obj$as.data.frame()
df$label.abrv <- substr(df$label, 1, 30) 
col_ix <- match(c('pval', 'fdr', 'label.abrv'), colnames(df))
df <- df[, c(col_ix, (1:ncol(df))[-col_ix])]
df$label <- NULL
rownames(df) <- NULL
df

```


### M2 
```{r 69267232684, fig.width=8.25, fig.align='center'}
hyp_obj <- tabsets[['NON-CARC']][['M2']] 



hyp_obj %>%
hyp_hmap(top=15,return_plots=1,show_plots=0)


df <- hyp_obj$as.data.frame()
df$label.abrv <- substr(df$label, 1, 30) 
col_ix <- match(c('pval', 'fdr', 'label.abrv'), colnames(df))
df <- df[, c(col_ix, (1:ncol(df))[-col_ix])]
df$label <- NULL
rownames(df) <- NULL
df

```


### M3 
```{r 57823908717, fig.width=8.25, fig.align='center'}
hyp_obj <- tabsets[['NON-CARC']][['M3']] 



hyp_obj %>%
hyp_hmap(top=15,return_plots=1,show_plots=0)


df <- hyp_obj$as.data.frame()
df$label.abrv <- substr(df$label, 1, 30) 
col_ix <- match(c('pval', 'fdr', 'label.abrv'), colnames(df))
df <- df[, c(col_ix, (1:ncol(df))[-col_ix])]
df$label <- NULL
rownames(df) <- NULL
df

```


### M4 
```{r 48129080679, fig.width=8.25, fig.align='center'}
hyp_obj <- tabsets[['NON-CARC']][['M4']] 



hyp_obj %>%
hyp_hmap(top=15,return_plots=1,show_plots=0)


df <- hyp_obj$as.data.frame()
df$label.abrv <- substr(df$label, 1, 30) 
col_ix <- match(c('pval', 'fdr', 'label.abrv'), colnames(df))
df <- df[, c(col_ix, (1:ncol(df))[-col_ix])]
df$label <- NULL
rownames(df) <- NULL
df

```


### M5 
```{r 15349289138, fig.width=8.25, fig.align='center'}
hyp_obj <- tabsets[['NON-CARC']][['M5']] 



hyp_obj %>%
hyp_hmap(top=15,return_plots=1,show_plots=0)


df <- hyp_obj$as.data.frame()
df$label.abrv <- substr(df$label, 1, 30) 
col_ix <- match(c('pval', 'fdr', 'label.abrv'), colnames(df))
df <- df[, c(col_ix, (1:ncol(df))[-col_ix])]
df$label <- NULL
rownames(df) <- NULL
df

```


### M6 
```{r 34602991877, fig.width=8.25, fig.align='center'}
hyp_obj <- tabsets[['NON-CARC']][['M6']] 



hyp_obj %>%
hyp_hmap(top=15,return_plots=1,show_plots=0)


df <- hyp_obj$as.data.frame()
df$label.abrv <- substr(df$label, 1, 30) 
col_ix <- match(c('pval', 'fdr', 'label.abrv'), colnames(df))
df <- df[, c(col_ix, (1:ncol(df))[-col_ix])]
df$label <- NULL
rownames(df) <- NULL
df

```


### M9 
```{r 87908003906, fig.width=8.25, fig.align='center'}
hyp_obj <- tabsets[['NON-CARC']][['M9']] 



hyp_obj %>%
hyp_hmap(top=15,return_plots=1,show_plots=0)


df <- hyp_obj$as.data.frame()
df$label.abrv <- substr(df$label, 1, 30) 
col_ix <- match(c('pval', 'fdr', 'label.abrv'), colnames(df))
df <- df[, c(col_ix, (1:ncol(df))[-col_ix])]
df$label <- NULL
rownames(df) <- NULL
df

```


### M10 
```{r 69753792200, fig.width=8.25, fig.align='center'}
hyp_obj <- tabsets[['NON-CARC']][['M10']] 



hyp_obj %>%
hyp_hmap(top=15,return_plots=1,show_plots=0)


df <- hyp_obj$as.data.frame()
df$label.abrv <- substr(df$label, 1, 30) 
col_ix <- match(c('pval', 'fdr', 'label.abrv'), colnames(df))
df <- df[, c(col_ix, (1:ncol(df))[-col_ix])]
df$label <- NULL
rownames(df) <- NULL
df

```


### M11 
```{r 72813073119, fig.width=8.25, fig.align='center'}
hyp_obj <- tabsets[['NON-CARC']][['M11']] 



hyp_obj %>%
hyp_hmap(top=15,return_plots=1,show_plots=0)


df <- hyp_obj$as.data.frame()
df$label.abrv <- substr(df$label, 1, 30) 
col_ix <- match(c('pval', 'fdr', 'label.abrv'), colnames(df))
df <- df[, c(col_ix, (1:ncol(df))[-col_ix])]
df$label <- NULL
rownames(df) <- NULL
df

```


### M12 
```{r 84360363206, fig.width=8.25, fig.align='center'}
hyp_obj <- tabsets[['NON-CARC']][['M12']] 



hyp_obj %>%
hyp_hmap(top=15,return_plots=1,show_plots=0)


df <- hyp_obj$as.data.frame()
df$label.abrv <- substr(df$label, 1, 30) 
col_ix <- match(c('pval', 'fdr', 'label.abrv'), colnames(df))
df <- df[, c(col_ix, (1:ncol(df))[-col_ix])]
df$label <- NULL
rownames(df) <- NULL
df

```


### M13 
```{r 66227088220, fig.width=8.25, fig.align='center'}
hyp_obj <- tabsets[['NON-CARC']][['M13']] 



hyp_obj %>%
hyp_hmap(top=15,return_plots=1,show_plots=0)


df <- hyp_obj$as.data.frame()
df$label.abrv <- substr(df$label, 1, 30) 
col_ix <- match(c('pval', 'fdr', 'label.abrv'), colnames(df))
df <- df[, c(col_ix, (1:ncol(df))[-col_ix])]
df$label <- NULL
rownames(df) <- NULL
df

```


### M16 
```{r 34058353264, fig.width=8.25, fig.align='center'}
hyp_obj <- tabsets[['NON-CARC']][['M16']] 



hyp_obj %>%
hyp_hmap(top=15,return_plots=1,show_plots=0)


df <- hyp_obj$as.data.frame()
df$label.abrv <- substr(df$label, 1, 30) 
col_ix <- match(c('pval', 'fdr', 'label.abrv'), colnames(df))
df <- df[, c(col_ix, (1:ncol(df))[-col_ix])]
df$label <- NULL
rownames(df) <- NULL
df

```


### M23 
```{r 70860512985, fig.width=8.25, fig.align='center'}
hyp_obj <- tabsets[['NON-CARC']][['M23']] 



hyp_obj %>%
hyp_hmap(top=15,return_plots=1,show_plots=0)


df <- hyp_obj$as.data.frame()
df$label.abrv <- substr(df$label, 1, 30) 
col_ix <- match(c('pval', 'fdr', 'label.abrv'), colnames(df))
df <- df[, c(col_ix, (1:ncol(df))[-col_ix])]
df$label <- NULL
rownames(df) <- NULL
df

```


### M30 
```{r 54887441445, fig.width=8.25, fig.align='center'}
hyp_obj <- tabsets[['NON-CARC']][['M30']] 



hyp_obj %>%
hyp_hmap(top=15,return_plots=1,show_plots=0)


df <- hyp_obj$as.data.frame()
df$label.abrv <- substr(df$label, 1, 30) 
col_ix <- match(c('pval', 'fdr', 'label.abrv'), colnames(df))
df <- df[, c(col_ix, (1:ncol(df))[-col_ix])]
df$label <- NULL
rownames(df) <- NULL
df

```


### M32 
```{r 65967902494, fig.width=8.25, fig.align='center'}
hyp_obj <- tabsets[['NON-CARC']][['M32']] 



hyp_obj %>%
hyp_hmap(top=15,return_plots=1,show_plots=0)


df <- hyp_obj$as.data.frame()
df$label.abrv <- substr(df$label, 1, 30) 
col_ix <- match(c('pval', 'fdr', 'label.abrv'), colnames(df))
df <- df[, c(col_ix, (1:ncol(df))[-col_ix])]
df$label <- NULL
rownames(df) <- NULL
df

```


# CARCINOGEN
##  {.tabset .tabset-fade}


### M0 
```{r 92261862045, fig.width=8.25, fig.align='center'}
hyp_obj <- tabsets[['CARCINOGEN']][['M0']] 



hyp_obj %>%
hyp_hmap(top=15,return_plots=1,show_plots=0)


df <- hyp_obj$as.data.frame()
df$label.abrv <- substr(df$label, 1, 30) 
col_ix <- match(c('pval', 'fdr', 'label.abrv'), colnames(df))
df <- df[, c(col_ix, (1:ncol(df))[-col_ix])]
df$label <- NULL
rownames(df) <- NULL
df

```


### M1 
```{r 68016216456, fig.width=8.25, fig.align='center'}
hyp_obj <- tabsets[['CARCINOGEN']][['M1']] 



hyp_obj %>%
hyp_hmap(top=15,return_plots=1,show_plots=0)


df <- hyp_obj$as.data.frame()
df$label.abrv <- substr(df$label, 1, 30) 
col_ix <- match(c('pval', 'fdr', 'label.abrv'), colnames(df))
df <- df[, c(col_ix, (1:ncol(df))[-col_ix])]
df$label <- NULL
rownames(df) <- NULL
df

```


### M2 
```{r 56519526762, fig.width=8.25, fig.align='center'}
hyp_obj <- tabsets[['CARCINOGEN']][['M2']] 



hyp_obj %>%
hyp_hmap(top=15,return_plots=1,show_plots=0)


df <- hyp_obj$as.data.frame()
df$label.abrv <- substr(df$label, 1, 30) 
col_ix <- match(c('pval', 'fdr', 'label.abrv'), colnames(df))
df <- df[, c(col_ix, (1:ncol(df))[-col_ix])]
df$label <- NULL
rownames(df) <- NULL
df

```


### M3 
```{r 40099877335, fig.width=8.25, fig.align='center'}
hyp_obj <- tabsets[['CARCINOGEN']][['M3']] 



hyp_obj %>%
hyp_hmap(top=15,return_plots=1,show_plots=0)


df <- hyp_obj$as.data.frame()
df$label.abrv <- substr(df$label, 1, 30) 
col_ix <- match(c('pval', 'fdr', 'label.abrv'), colnames(df))
df <- df[, c(col_ix, (1:ncol(df))[-col_ix])]
df$label <- NULL
rownames(df) <- NULL
df

```


### M4 
```{r 62615107108, fig.width=8.25, fig.align='center'}
hyp_obj <- tabsets[['CARCINOGEN']][['M4']] 



hyp_obj %>%
hyp_hmap(top=15,return_plots=1,show_plots=0)


df <- hyp_obj$as.data.frame()
df$label.abrv <- substr(df$label, 1, 30) 
col_ix <- match(c('pval', 'fdr', 'label.abrv'), colnames(df))
df <- df[, c(col_ix, (1:ncol(df))[-col_ix])]
df$label <- NULL
rownames(df) <- NULL
df

```


### M6 
```{r 78551463394, fig.width=8.25, fig.align='center'}
hyp_obj <- tabsets[['CARCINOGEN']][['M6']] 



hyp_obj %>%
hyp_hmap(top=15,return_plots=1,show_plots=0)


df <- hyp_obj$as.data.frame()
df$label.abrv <- substr(df$label, 1, 30) 
col_ix <- match(c('pval', 'fdr', 'label.abrv'), colnames(df))
df <- df[, c(col_ix, (1:ncol(df))[-col_ix])]
df$label <- NULL
rownames(df) <- NULL
df

```


### M7 
```{r 9482826437, fig.width=8.25, fig.align='center'}
hyp_obj <- tabsets[['CARCINOGEN']][['M7']] 



hyp_obj %>%
hyp_hmap(top=15,return_plots=1,show_plots=0)


df <- hyp_obj$as.data.frame()
df$label.abrv <- substr(df$label, 1, 30) 
col_ix <- match(c('pval', 'fdr', 'label.abrv'), colnames(df))
df <- df[, c(col_ix, (1:ncol(df))[-col_ix])]
df$label <- NULL
rownames(df) <- NULL
df

```


### M8 
```{r 25871766484, fig.width=8.25, fig.align='center'}
hyp_obj <- tabsets[['CARCINOGEN']][['M8']] 



hyp_obj %>%
hyp_hmap(top=15,return_plots=1,show_plots=0)


df <- hyp_obj$as.data.frame()
df$label.abrv <- substr(df$label, 1, 30) 
col_ix <- match(c('pval', 'fdr', 'label.abrv'), colnames(df))
df <- df[, c(col_ix, (1:ncol(df))[-col_ix])]
df$label <- NULL
rownames(df) <- NULL
df

```


### M9 
```{r 54383829269, fig.width=8.25, fig.align='center'}
hyp_obj <- tabsets[['CARCINOGEN']][['M9']] 



hyp_obj %>%
hyp_hmap(top=15,return_plots=1,show_plots=0)


df <- hyp_obj$as.data.frame()
df$label.abrv <- substr(df$label, 1, 30) 
col_ix <- match(c('pval', 'fdr', 'label.abrv'), colnames(df))
df <- df[, c(col_ix, (1:ncol(df))[-col_ix])]
df$label <- NULL
rownames(df) <- NULL
df

```


### M13 
```{r 41052197298, fig.width=8.25, fig.align='center'}
hyp_obj <- tabsets[['CARCINOGEN']][['M13']] 



hyp_obj %>%
hyp_hmap(top=15,return_plots=1,show_plots=0)


df <- hyp_obj$as.data.frame()
df$label.abrv <- substr(df$label, 1, 30) 
col_ix <- match(c('pval', 'fdr', 'label.abrv'), colnames(df))
df <- df[, c(col_ix, (1:ncol(df))[-col_ix])]
df$label <- NULL
rownames(df) <- NULL
df

```


### M15 
```{r 4049427911, fig.width=8.25, fig.align='center'}
hyp_obj <- tabsets[['CARCINOGEN']][['M15']] 



hyp_obj %>%
hyp_hmap(top=15,return_plots=1,show_plots=0)


df <- hyp_obj$as.data.frame()
df$label.abrv <- substr(df$label, 1, 30) 
col_ix <- match(c('pval', 'fdr', 'label.abrv'), colnames(df))
df <- df[, c(col_ix, (1:ncol(df))[-col_ix])]
df$label <- NULL
rownames(df) <- NULL
df

```


### M16 
```{r 34249972183, fig.width=8.25, fig.align='center'}
hyp_obj <- tabsets[['CARCINOGEN']][['M16']] 



hyp_obj %>%
hyp_hmap(top=15,return_plots=1,show_plots=0)


df <- hyp_obj$as.data.frame()
df$label.abrv <- substr(df$label, 1, 30) 
col_ix <- match(c('pval', 'fdr', 'label.abrv'), colnames(df))
df <- df[, c(col_ix, (1:ncol(df))[-col_ix])]
df$label <- NULL
rownames(df) <- NULL
df

```


### M18 
```{r 41257669628, fig.width=8.25, fig.align='center'}
hyp_obj <- tabsets[['CARCINOGEN']][['M18']] 



hyp_obj %>%
hyp_hmap(top=15,return_plots=1,show_plots=0)


df <- hyp_obj$as.data.frame()
df$label.abrv <- substr(df$label, 1, 30) 
col_ix <- match(c('pval', 'fdr', 'label.abrv'), colnames(df))
df <- df[, c(col_ix, (1:ncol(df))[-col_ix])]
df$label <- NULL
rownames(df) <- NULL
df

```


### M19 
```{r 54084353260, fig.width=8.25, fig.align='center'}
hyp_obj <- tabsets[['CARCINOGEN']][['M19']] 



hyp_obj %>%
hyp_hmap(top=15,return_plots=1,show_plots=0)


df <- hyp_obj$as.data.frame()
df$label.abrv <- substr(df$label, 1, 30) 
col_ix <- match(c('pval', 'fdr', 'label.abrv'), colnames(df))
df <- df[, c(col_ix, (1:ncol(df))[-col_ix])]
df$label <- NULL
rownames(df) <- NULL
df

```


### M23 
```{r 85631354893, fig.width=8.25, fig.align='center'}
hyp_obj <- tabsets[['CARCINOGEN']][['M23']] 



hyp_obj %>%
hyp_hmap(top=15,return_plots=1,show_plots=0)


df <- hyp_obj$as.data.frame()
df$label.abrv <- substr(df$label, 1, 30) 
col_ix <- match(c('pval', 'fdr', 'label.abrv'), colnames(df))
df <- df[, c(col_ix, (1:ncol(df))[-col_ix])]
df$label <- NULL
rownames(df) <- NULL
df

```

