test_that("hyp object is working", {
    data <- data.frame(replicate(5,sample(0:1,10,rep=TRUE)))
    args <- list("arg_1"=1, "arg_2"=2, "arg_3"=3)
    hyp_obj <- hyp$new(data, args)
    expect_is(hyp_obj, "hyp")
    expect_is(hyp_obj, "R6")
    expect_output(print(hyp_obj))
    expect_is(hyp_obj$as.data.frame(), "data.frame")
    expect_equal(names(hyp_obj$args), c("arg_1", "arg_2", "arg_3"))
    expect_equal(dim(hyp_obj$data), c(10, 5))
})

test_that("multihyp object is working", {
    data <- data.frame(replicate(5,sample(0:1,10,rep=TRUE)))
    args <- list("arg_1"=1, "arg_2"=2, "arg_3"=3)
    hyp_obj <- hyp$new(data, args)
    data <- list("hyp_1"=hyp_obj, "hyp_2"=hyp_obj,"hyp_3"=hyp_obj)
    multihyp_obj <- multihyp$new(data)
    expect_is(multihyp_obj, "multihyp")
    expect_is(multihyp_obj, "R6")
    expect_equal(names(multihyp_obj$data), c("hyp_1", "hyp_2", "hyp_3"))
    expect_is(multihyp_obj$as.list(), "list")
    expect_equal(names(multihyp_obj$as.list()), c("hyp_1", "hyp_2", "hyp_3"))
    expect_equal(dim(multihyp_obj$as.list()[[1]]), c(10, 5))
})

test_that("pvector object is working", {
    pv <- pvector$new(c(1,2,3,4,5))
    expect_is(pv, "pvector")
    expect_is(pv, "R6")
    popped <- pv$pop()
    expect_equal(popped, 1)
    expect_output(print(pv))
    expect_equal(pv$values, c(2,3,4,5))
    expect_equal(pv$length(), 4)
    pv$push(6)
    pv$push(c(7,8))
    expect_output(print(pv))
    expect_equal(pv$values, c(2,3,4,5,6,7,8))
    pv <- pvector$new(c(1,2))
    popped <- pv$pop()
    popped <- pv$pop()
    expect_equal(pv$length(), 0)
    popped <- pv$pop()
    expect_null(popped)
    expect_equal(pv$length(), 0)
})
