test_that("hyp object is working", {
    data <- data.frame(replicate(5,sample(0:1,10,rep=TRUE)))
    args <- list("arg_1"=1, "arg_2"=2, "arg_3"=3)
    hyp_obj <- hyp$new(data, args)
    expect_is(hyp_obj, "hyp")
    expect_is(hyp_obj, "R6")
    expect_output(print(hyp_obj))
    expect_is(hyp_obj$as.data.frame(), "data.frame")
    expect_equal(names(hyp_obj$args), c("arg_1", "arg_2", "arg_3"))
    expect_equal(dim(hyp_obj$data), c(10, 5))
})

test_that("multihyp object is working", {
    data <- data.frame(replicate(5,sample(0:1,10,rep=TRUE)))
    args <- list("arg_1"=1, "arg_2"=2, "arg_3"=3)
    hyp_obj <- hyp$new(data, args)
    data <- list("hyp_1"=hyp_obj, "hyp_2"=hyp_obj,"hyp_3"=hyp_obj)
    multihyp_obj <- multihyp$new(data)
    expect_is(multihyp_obj, "multihyp")
    expect_is(multihyp_obj, "R6")
    expect_equal(names(multihyp_obj$data), c("hyp_1", "hyp_2", "hyp_3"))
    expect_is(multihyp_obj$as.list(), "list")
    expect_equal(names(multihyp_obj$as.list()), c("hyp_1", "hyp_2", "hyp_3"))
    expect_equal(dim(multihyp_obj$as.list()[[1]]), c(10, 5))
})

test_that("pvector object is working", {
    pv <- pvector$new(c(1,2,3,4,5))
    expect_is(pv, "pvector")
    expect_is(pv, "R6")
    popped <- pv$pop()
    expect_equal(popped, 1)
    expect_output(print(pv))
    expect_equal(pv$values, c(2,3,4,5))
    expect_equal(pv$length(), 4)
    pv$push(6)
    pv$push(c(7,8))
    expect_output(print(pv))
    expect_equal(pv$values, c(2,3,4,5,6,7,8))
    pv <- pvector$new(c(1,2))
    popped <- pv$pop()
    popped <- pv$pop()
    expect_equal(pv$length(), 0)
    popped <- pv$pop()
    expect_null(popped)
    expect_equal(pv$length(), 0)
})

test_that("rgsets object is working", {
    testdat <- readRDS(file.path(system.file("extdata", package="hypeR"), "testdat.rds"))
    rgsets_obj <- rgsets$new(gsets=testdat$gsets,
                             nodes=testdat$nodes,
                             edges=testdat$edges)
    expect_is(rgsets_obj, "rgsets")
    expect_is(rgsets_obj, "R6")   
    expect_output(print(rgsets_obj))
    expect_equal(names(rgsets_obj$gsets)[1:3], c("Leaf Geneset 1", "Leaf Geneset 2", "Leaf Geneset 3"))
    expect_equal(colnames(rgsets_obj$nodes), c("label", "id", "length"))
    expect_equal(rgsets_obj$nodes["G10", "length"], 13)
    expect_equal(rgsets_obj$nodes["G12", "length"], length(unique(c(rgsets_obj$gsets[["Leaf Geneset 7"]],
                                                                    rgsets_obj$gsets[["Leaf Geneset 8"]],
                                                                    rgsets_obj$gsets[["Leaf Geneset 9"]]))))
    
    expect_equal(colnames(rgsets_obj$edges), c("from", "to"))
    expect_equal(dim(rgsets_obj$edges), c(10,2))
    rgsets_obj_subset <- rgsets_obj$subset(c("Leaf Geneset 1", "Leaf Geneset 5", "Leaf Geneset 8"))
    expect_equivalent(c("G1","G11","G12","G13","G14","G15","G5","G8"), sort(rgsets_obj_subset$nodes$id))
    expect_equal(names(rgsets_obj_subset$gsets), c("Leaf Geneset 1", "Leaf Geneset 5", "Leaf Geneset 8"))
    expect_equal(dim(rgsets_obj_subset$edges), c(6,2))
    expect_equal(dim(rgsets_obj$edges), c(10,2))
})
